language: python

os: linux

dist: xenial

install: pip install tox

script: tox

jobs:
    include:
        - { python: "3.8", env: TOXENV=py38-django22 }
        - { python: "3.8", env: TOXENV=py38-django30 }
        - { python: "3.8", env: TOXENV=py38-django31 }
        - { python: "3.8", env: TOXENV=py38-djangomaster }
        - { python: "3.8", env: TOXENV=checks }
        - { python: "3.8", env: TOXENV=fmt }
        - { python: "3.8", env: TOXENV=lint }
        - { python: "3.8", env: TOXENV=mypy }
        - { python: "3.9", env: TOXENV=py39-djangomaster }
    allow_failures:
        - { python: "3.9", env: TOXENV=py39-djangomaster }
